// angular/src/app/pages/profile.component.ts
import { Component, effect, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../auth/auth.service';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <div class="page-profile">
      <div>
        <h1>Profile</h1>
        <p class="subtitle">Update the details on your IdP account.</p>
      </div>

      <form class="profile-form" [formGroup]="form" (ngSubmit)="save()">
        @if (status(); as msg) {
          <div class="status" [class.status--success]="msg.type === 'success'" [class.status--error]="msg.type === 'error'" role="alert">
            {{ msg.message }}
          </div>
        }

        <div class="field">
          <label for="name">First name</label>
          <input id="name" type="text" formControlName="name" />
        </div>

        <div class="field">
          <label for="surname">Last name</label>
          <input id="surname" type="text" formControlName="surname" />
        </div>

        <div class="field">
          <label for="email">Email</label>
          <input id="email" type="email" formControlName="email" />
        </div>

        <div class="form-actions">
          <button type="submit" class="btn btn-primary" [disabled]="saving()">
            {{ saving() ? 'Saving…' : 'Save changes' }}
          </button>
        </div>
      </form>
    </div>
  `,
})
export class ProfileComponent {
  private readonly auth = inject(AuthService);
  private readonly fb = inject(FormBuilder);

  protected readonly saving = signal(false);
  protected readonly status = signal<{ type: 'success' | 'error'; message: string } | null>(null);

  protected readonly form = this.fb.nonNullable.group({
    name: [''],
    surname: [''],
    email: ['', Validators.email],
  });

  constructor() {
    effect(() => {
      const user = this.auth.currentUser()?.user;
      if (!user) return;
      this.form.patchValue({
        name: user.name ?? '',
        surname: user.surname ?? '',
        email: user.emailAddress ?? '',
      });
    });
  }

  protected async save() {
    this.status.set(null);
    this.saving.set(true);
    try {
      const value = this.form.getRawValue();
      await this.auth.updateUserProfile(value);
      this.status.set({ type: 'success', message: 'Profile updated.' });
    } catch (error) {
      this.status.set({
        type: 'error',
        message: error instanceof Error ? error.message : 'Could not update profile.',
      });
    } finally {
      this.saving.set(false);
    }
  }
}

// crm/src/pages/Profile.jsx
import { useEffect, useState } from 'react';
import { useAuthContext } from '@/auth';
import { Card, Button, Field, Input, PageHeader } from '@/components/ui';

const Profile = () => {
  const { headerUser, updateUser } = useAuthContext();
  const user = headerUser?.user;

  const [form, setForm] = useState({ name: '', surname: '', email: '' });
  const [saving, setSaving] = useState(false);
  const [status, setStatus] = useState(null);

  useEffect(() => {
    setForm({
      name: user?.name ?? '',
      surname: user?.surname ?? '',
      email: user?.emailAddress ?? '',
    });
  }, [user?.name, user?.surname, user?.emailAddress]);

  const handleChange = (field) => (event) => {
    setForm((prev) => ({ ...prev, [field]: event.target.value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setStatus(null);
    setSaving(true);
    try {
      await updateUser({ name: form.name, surname: form.surname, email: form.email });
      setStatus({ type: 'success', message: 'Profile updated.' });
    } catch (error) {
      setStatus({ type: 'error', message: error?.message || 'Could not update profile.' });
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="mx-auto flex w-full max-w-xl flex-col gap-6">
      <PageHeader title="Profile" subtitle="Update the details on your IdP account." />

      <Card bodyClass="p-6">
        <form onSubmit={handleSubmit} className="flex flex-col gap-5">
          {status && (
            <div
              className={[
                'rounded-lg px-4 py-3 text-sm',
                status.type === 'success'
                  ? 'bg-emerald-50 text-emerald-700'
                  : 'bg-rose-50 text-rose-700',
              ].join(' ')}
            >
              {status.message}
            </div>
          )}

          <Field label="First name">
            <Input id="name" type="text" value={form.name} onChange={handleChange('name')} />
          </Field>

          <Field label="Last name">
            <Input id="surname" type="text" value={form.surname} onChange={handleChange('surname')} />
          </Field>

          <Field label="Email">
            <Input id="email" type="email" value={form.email} onChange={handleChange('email')} />
          </Field>

          <div className="flex items-center justify-end">
            <Button type="submit" loading={saving}>
              Save changes
            </Button>
          </div>
        </form>
      </Card>
    </div>
  );
};

export { Profile };
