// react/src/pages/Home.jsx
import { useAuthContext } from '@/auth';
import { getProfileDisplayName } from '@/auth';

const Home = () => {
  const { headerUser } = useAuthContext();
  const user = headerUser?.user;
  const displayName = getProfileDisplayName({
    name: user?.name,
    surname: user?.surname,
    email: user?.emailAddress,
  });

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-semibold text-gray-900">Welcome back, {displayName}</h1>
        <p className="mt-1 text-sm text-gray-600">
          You are signed in via the IdP login flow. This is a placeholder home page.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        {['Overview', 'Activity', 'Settings'].map((title) => (
          <div key={title} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
            <p className="text-sm font-medium text-gray-900">{title}</p>
            <p className="mt-1 text-xs text-gray-500">Placeholder content.</p>
          </div>
        ))}
      </div>

      <div className="rounded-xl border border-dashed border-gray-300 bg-white p-8 text-center text-sm text-gray-500">
        Start building your app here.
      </div>
    </div>
  );
};

export { Home };

// angular/src/app/pages/home.component.ts
import { Component, inject } from '@angular/core';
import { AuthService } from '../auth/auth.service';
import { getProfileDisplayName } from '../auth/idp-profile.models';

@Component({
  selector: 'app-home',
  standalone: true,
  template: `
    <div class="page-home">
      <div>
        <h1>Welcome back, {{ displayName() }}</h1>
        <p class="subtitle">
          You are signed in via the IdP login flow. This is a placeholder home page.
        </p>
      </div>

      <div class="card-grid">
        @for (title of cards; track title) {
          <div class="card">
            <p class="card-title">{{ title }}</p>
            <p class="card-text">Placeholder content.</p>
          </div>
        }
      </div>

      <div class="placeholder-box">Start building your app here.</div>
    </div>
  `,
})
export class HomeComponent {
  private readonly auth = inject(AuthService);
  protected readonly cards = ['Overview', 'Activity', 'Settings'];

  protected displayName() {
    const user = this.auth.currentUser()?.user;
    return getProfileDisplayName({
      name: user?.name,
      surname: user?.surname,
      emailAddress: user?.emailAddress,
    });
  }
}
