// react/src/App.jsx
export default function App() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-slate-950 px-6 text-center text-white">
      <p className="mb-2 text-sm uppercase tracking-widest text-slate-400">Cloudgate</p>
      <h1 className="mb-4 text-4xl font-bold">React + Vite Starter</h1>
      <p className="max-w-md text-slate-300">
        Edit <code className="rounded bg-slate-800 px-1.5 py-0.5 font-mono text-sm">src/App.jsx</code>{' '}
        and save to see changes. Run <code className="font-mono text-sm">npm run build</code> when you are
        ready to publish.
      </p>
    </div>
  );
}

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
    <div class="page">
      <p class="eyebrow">Cloudgate</p>
      <h1>Angular Starter</h1>
      <p class="lead">
        Edit <code>src/app/app.component.ts</code> and save to see changes. Run
        <code>npm run build</code> when you are ready to publish.
      </p>
    </div>
    <router-outlet />
  `,
})
export class AppComponent {}
